import "dotenv/config";
import express from "express";
import cors from "cors";
import rootRoute from "./routes/rootRoute.js";
import authRoute from "./routes/authRoute.js";
const app = express();
app.use(express.json());
app.use(cors());
app.use(rootRoute);
app.use(authRoute);
app.listen(process.env.PORTA);
