services:
  mywallet-back:
    container_name: mywallet-back
    build: .
    restart: always
    env_file:
     - .env
    expose:
      - $PORT
    ports:
      - $PORT:$PORT
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    env_file:
     - .env