services:
  back-batepapo-uol:
    container_name: back-batepapo-uol
    build: .
    restart: always
    env_file:
     - .env
    expose:
      - $PORT_HOST
    ports:
      - $PORT_HOST:$PORT_HOST
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    env_file:
     - .env